-- Create file to test hbnb_test_db with some data

DROP DATABASE IF EXISTS HBNB_MYSQL_DB;

CREATE DATABASE HBNB_MYSQL_DB;

USE HBNB_MYSQL_DB;

CREATE USER IF NOT EXISTS 'HBNB_MYSQL_USER'@'HBNB_MYSQL_HOST' IDENTIFIED BY 'HBNB_MYSQL_PWD';

GRANT ALL PRIVILEGES ON HBNB_MYSQL_DB.* TO 'HBNB_MYSQL_USER'@'HBNB_MYSQL_HOST';

FLUSH PRIVILEGES;
